# Base configs
baseurl: "https://necofilm.github.io/"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: " "

# UI configs
title: "Photography by NeCo Flims"
subtitle: "Fantasy photography"
author: "NeCo Flims"
header:
 title: "Photography"
 subtitle: "by NeCo Flims"
footer:
 name: "Hello"
 bio: "I'm your fantasy photographer. Let me make your photography and filmography dreams come true."
 #github: ""

social_urls:
  #twitter: "https://www.twitter.com/"
  instagram: "https://www.instagram.com/outd00rb00tyb00bie/"
  #dribbble: "https://dribbble.com/"
  #linkedin: "https://in.linkedin.com/in/"
  #github: "https://www.github.com/necofilms"
  gmail: "mailto:necoentertainers@gmail.com"

# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "fa fa-camera-retro"}, {"tag": "FNumber", "icon": "far fa-dot-circle"}, {"tag": "ExposureTime", "icon": "far fa-clock"}, {"tag": "ISOSpeedRatings", "icon": "fa fa-info-circle"}]'
